version: '3.8'

services:
  hcm-hub-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hcm_hub_dashboard_app
    ports:
      - "5173:80"
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./public/data:/usr/share/nginx/html/public/data
    restart: unless-stopped
